### ISSUE TITLE
Move Akrivis and YaRD from kiegroup to kubesmarts

### ISSUE THREAD

**Issue by lucamolteni** [kubesmarts/akrivis#34]
Kiegroup shouldn't be used anymore

**Comment by lucamolteni** [comment]
assigning @mareknovotny as he's the only one that can do it 

"Read the warnings about potential loss of features depending on the new owner's GitHub subscription."

**Comment by mareknovotny** [comment]
https://github.com/kubesmarts/yard and https://github.com/kubesmarts/akrivis transferred
